/**
 * Response containing external calendar URLs for an event.
 *
 * Aligned with backend DTO: CalendarUrlsResponse
 *
 * @description
 * These URLs are generated by the backend and allow users to
 * quickly add an event to their preferred external calendar.
 * When opened in a browser, they pre-fill the event details.
 *
 * @example
 * ```typescript
 * const urls: CalendarUrlsResponse = {
 *   googleCalendarUrl: 'https://calendar.google.com/calendar/render?action=TEMPLATE&...',
 *   outlookWebUrl: 'https://outlook.office.com/calendar/action/compose?...'
 * };
 *
 * // Open Google Calendar in new tab
 * window.open(urls.googleCalendarUrl, '_blank');
 * ```
 */
export interface CalendarUrlsResponse {
  /**
   * Google Calendar quick-add URL.
   *
   * Opens Google Calendar with the event pre-filled.
   * User must be logged into their Google account.
   */
  googleCalendarUrl: string;

  /**
   * Outlook Web quick-add URL.
   *
   * Opens Outlook Web with the event pre-filled.
   * User must be logged into their Microsoft account.
   */
  outlookWebUrl: string;
}

/**
 * Enum representing supported external calendar providers.
 *
 * @description
 * Used in the export modal to let users choose their preferred calendar.
 */
export enum ExternalCalendarProvider {
  GOOGLE = 'GOOGLE',
  OUTLOOK = 'OUTLOOK',
  APPLE = 'APPLE',
  ICS = 'ICS'
}

/**
 * Display names for external calendar providers (French localization).
 */
export const EXTERNAL_CALENDAR_PROVIDER_LABELS: Record<ExternalCalendarProvider, string> = {
  [ExternalCalendarProvider.GOOGLE]: 'Google Calendar',
  [ExternalCalendarProvider.OUTLOOK]: 'Outlook',
  [ExternalCalendarProvider.APPLE]: 'Apple Calendar',
  [ExternalCalendarProvider.ICS]: 'Fichier ICS'
};

/**
 * Icons for external calendar providers.
 *
 * @description
 * Can be used with icon libraries or as image asset names.
 */
export const EXTERNAL_CALENDAR_PROVIDER_ICONS: Record<ExternalCalendarProvider, string> = {
  [ExternalCalendarProvider.GOOGLE]: 'google',
  [ExternalCalendarProvider.OUTLOOK]: 'microsoft',
  [ExternalCalendarProvider.APPLE]: 'apple',
  [ExternalCalendarProvider.ICS]: 'file-download'
};

/**
 * Options for exporting calendar events.
 *
 * @description
 * Used by the export modal/service to determine what to export and how.
 */
export interface CalendarExportOptions {
  /** Target calendar provider */
  provider: ExternalCalendarProvider;

  /** Whether to export a single event or all user events */
  exportAll: boolean;

  /** Event public ID (required if exportAll is false) */
  eventPublicId?: string;
}
